# Generated by Django 4.0.4 on 2022-05-31 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wallet.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0, validators=[wallet.validators.validate_positive_score], verbose_name='Баланс')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование кошелька')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(validators=[wallet.validators.validate_positive_score], verbose_name='Сумма перевода')),
                ('dst_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dst_transfers', to='wallet.wallet', verbose_name='Счет получателя')),
                ('src_wallet', models.ManyToManyField(related_name='src_transfers', to='wallet.wallet', verbose_name='Мои счета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
